# docker run --name api-solid-pg -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker 
# -e POSTGRESQL_DATABASE=apisolid -p 5432:5432 bitnami/postgresql:latest

# "reescrevendo" o comando acima, pra quem baixar a aplicação não precisar rodar o comando na máquina, apenas rodar o esse arquivo docker-compose

version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid